config/routes.rb
Rails.application.routes.draw do
  root "projects#index"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  resources :projects do
   resources :tickets 
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  has_many :tickets, dependent: :delete_all
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render "new"
    end
  end

  def show
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated"
      render "edit"
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project has been destroy."
    redirect_to projects_path
  end
  
  private
  def project_params
    params.require(:project).permit(:name, :description)
  end
  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert]= "The project you were looking for could be not found."
    redirect_to projects_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create 
    user = User.where(:name => params[:signin][:name]).first
    if user && user.authenticate(params[:signin][:password])
      session[:user_id] = user.id
      flash[:notice] = "Signed in successfully."
      redirect_to root_url
    else
      flash[:error] = "Sorry."
      render :new
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  def new
    @ticket = @project.tickets.build
  end

  def show
      
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been created"
      render "new"
    end
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."
    redirect_to @project
  end

  private 
  def set_project
    @project = Project.find(params[:project_id])
  end

  def ticket_params
    params.require(:ticket).permit(:title, :description)
  end

  def set_ticket
    @ticket = @project.tickets.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You have signed up successfullly."
      redirect_to projects_path
    else
      render :new
    end
  end

  private 
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join("-")
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<%= link_to "Home" , root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if content_for?(:title) %>
        <%= yield(:title) %>
      <% else %>
        Ticketee
      <% end %>
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <li> <%= link_to "Sign up", new_user_path%> </li>
      <li> <%= link_to "Sign in", signin_path%> </li>

    </nav>
    <% flash.each do |key, value| %>
    <div class= "flash" id="<%= key %>" >
      <%= value %>
    </div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
 <% if @project.errors.any? %>
  <div id = "error_explanation">
    <h2><%= pluralize(@project.errors.count, "error")%>
      prohibited this project from being saved:
    </h2>
    <ul>
      <% @project.errors.full_messages.each do  |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
 <% end %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name%>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_field :description %> <br/> <br>

    <%= f.submit %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>
<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h2> New Project</h2>
<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name, "Project") %>
<h2><%= @project.name %></h2>
<%= link_to "Edit Project", edit_project_path(@project) %>
<%= link_to "Delete Project",
    project_path(@project),
    method: :delete,
    data: { confirm: "Are yo sure you want to delete this project"
    } %>
<%= link_to "New Ticket", new_project_ticket_path(@project) %>
<ul id="ticket">
  <% @project.tickets.each do |ticket|%>
  <li>
    #<%= ticket.id%> - <%= link_to ticket.title, [@project, ticket]%>
  </li>
  <% end %>
</ul>

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %>
 <% if @ticket.errors.any? %>
  <div id = "error_explanation">
    <h2><%= pluralize(@project.errors.count, "error")%>
      prohibited this project from being saved:
    </h2>
    <ul>
      <% @ticket.errors.full_messages.each do  |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
 <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title%>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %> <br/> <br>

    <%= f.submit %>
  </p>
<% end %>

app/views/tickets/edit.html.erb
<h2>Editing a ticket in <%= @project.name %></h2>
<%= render "form" %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render "form"%>

app/views/tickets/show.html.erb
<div id="ticket">
  <h2><%= @ticket.title%></h2>
  <%= link_to "Edit Ticket", [:edit, @project, @ticket] %>
  <%= link_to "Delete Ticket", [@project,@ticket], method: :delete,
  data: {confirm: "Are you sure want to delete this ticket?"} %>
  <%= simple_format(@ticket.description) %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
 <% if @user.errors.any? %>
  <div id = "error_explanation">
    <h2><%= pluralize(@user.errors.count, "error")%>
      prohibited this project from being saved:
    </h2>
    <ul>
      <% @ticket.errors.full_messages.each do  |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
 <% end %>
  <p>
    <%= f.label :name, "Username" %>
    <%= f.text_field :name%>
  </p>
  <p>
    <%= f.label :email, "" %>
    <%= f.text_field :email%>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.text_field :password %> <br/> <br>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %> <br/> <br>
  </p>
  <%= f.submit "Sign Up"%>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form"%>

app/views/users/show.html.erb
show.html.erb